apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-qingcloud
spec:
  selector:
    matchLabels:
      app: nginx-csi
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-csi
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /mnt
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: qingcloud-pvc
          readOnly: false

